### ISSUE TITLE
Authentication error problem

### ISSUE THREAD

**Issue by linux858** [jsoctocat/BDO-Launcher#11] opened 2021-07-19 11:12 UTC
I keep getting these messages. 

https://i.vgy.me/2SDpZZ.png

https://i.vgy.me/wDLcxl.png

My login information and otp saved and correct, i have been login with same information before and not changed 

I tried to remove OTP password and leave it blank. when i log in it prompt me for OTP password and after i type OTP password i got this error

https://i.vgy.me/RAxu01.png

**Error details**

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Launcher.MainForm.<>c__DisplayClass21_0.<<OneTimePasswordAsync>g__OkButton_Click|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Launcher
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Hany/Desktop/BDO/Launcher.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 11.0.0.0
    Win32 Version: 11.0.1.21818
    CodeBase: file:///C:/Users/Hany/Desktop/BDO/Newtonsoft.Json.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

`

**Comment by teal-mkd** [comment] 2021-07-19 17:26
Getting the same errors, except I have no option to get a stack trace or debugging info. Stock launcher works, User/pass have been verified & re-entered.

**Comment by jsoctocat** [comment] 2021-07-19 18:03
ok, I'm on it, thanks for letting me know

**Comment by jsoctocat** [comment] 2021-07-19 19:06
I cannot reproduce this issue, try log into the website, maybe the password has been expired?

**Comment by jsoctocat** [comment] 2021-07-19 19:10
apparently this issue is caused by PA's side
https://www.reddit.com/r/blackdesertonline/comments/lupysv/anybody_knows_how_to_fix_this_problem_on_pc/
https://www.reddit.com/r/blackdesertonline/comments/lsw3wg/javascript_alert_your_access_has_been_denied/
https://www.reddit.com/r/blackdesertonline/comments/lufup6/your_access_has_been_denied_while_attempting_to/

try VPN or change NAT type to open (there is a linked video in one of the reddit thread)

**Comment by linux858** [comment] 2021-07-21 23:31
I dont live in NA or EU region and I login to offical PA launcher wihout vpn and my NAT already open. before that, kakao publisher was restricted to login by ip but not with PA anymore which is a really good thing. 

your launcher works with me randomly like it can log me in on 1st try or i have to keep login after 20 tries... 

can u try to login to EU then switch to NA and try again? maybe that will trigger the error for you?

its so frustrating to report this issue because happen randomly and I don't know what actually triggers it.

**Comment by jsoctocat** [comment] 2021-07-22 08:01
sure, I will look into it, also the next time an error pops up, screenshot it, it would greatly help me narrow down to what's causing the issue.

**Comment by Person7557** [comment] 2021-12-01 17:27
> 

all This mambo jumbo means that you have the "check for updates" option ticket. as @jsoctocat said in previous topic open by me, its non functional at this time, so untick those, and this error goes away.

Regarding 1/20, i would say its delay on your network maybe? Even though for me it works 1/3 attempts usually.

**Comment by Person7557** [comment] 2021-12-06 01:03
@jsoctocat you can close this topic in my opinion, the launcher is working as it should right now, and this error spam is only happening if you "check game version" as you launch the application, as it lacks admin privilages to inspect the file.

**Closed** 2021-12-06 03:44 UTC
